FROM node:20-bookworm-slim AS deps

WORKDIR /app

COPY package*.json ./
RUN npm ci --no-audit --no-fund

FROM node:20-bookworm-slim AS build

WORKDIR /app
ENV NODE_ENV=production \
    BUILD_ADAPTER=node

# Build-time envs for import.meta.env (VITE_*) only
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_DATABASE_URL
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID
ARG VITE_NOTIFICATIONS_API_URL
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_DATABASE_URL=$VITE_FIREBASE_DATABASE_URL \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
    VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID \
    VITE_NOTIFICATIONS_API_URL=$VITE_NOTIFICATIONS_API_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run prepare && npm run build

FROM node:20-bookworm-slim AS prod-deps

WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev --omit=optional --no-audit --no-fund && npm cache clean --force

FROM gcr.io/distroless/nodejs20-debian12:nonroot AS runner

ARG DATABASE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG YOOKASSA_SHOP_ID
ARG YOOKASSA_SECRET_KEY
ARG GROQ_API_KEY
ARG SESSION_SECRET
ARG BOT_DATABASE
ARG TELEGRAM_BOT_TOKEN
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG ONLINE_SECRET
WORKDIR /app

ENV NODE_ENV=production \
    HOST=0.0.0.0 \
    PORT=5173 \
    DATABASE_URL=${DATABASE_URL:-} \
    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-} \
    YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID:-} \
    YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY:-} \
    GROQ_API_KEY=${GROQ_API_KEY:-} \
    SESSION_SECRET=${SESSION_SECRET:-} \
    BOT_DATABASE=${BOT_DATABASE:-} \
    TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-} \
    REDIS_HOST=${REDIS_HOST:-} \
    REDIS_PORT=${REDIS_PORT:-} \
    REDIS_PASSWORD=${REDIS_PASSWORD:-} \
    ONLINE_SECRET=${ONLINE_SECRET:-}
    
COPY --chown=nonroot:nonroot --from=prod-deps /app/node_modules ./node_modules
COPY --chown=nonroot:nonroot --from=build /app/build ./build

EXPOSE 5173

USER nonroot

CMD ["build/index.js"]